# This syncs the GitHub Pages from the repo and presents it at https://sec-o-simple.github.io

name: Sec-O-Simple Website

# Run only on schedule and manually
on:
  workflow_dispatch:
  schedule:
     - cron:  '37 6 * * *'

permissions:
  contents: write
  pages: write
  actions: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
      - name: Checkout built GitHub Pages from sec-o-simple
        uses: actions/checkout@v4
        with:
           repository: sec-o-simple/sec-o-simple
           ref: gh-pages
           path: sec-o-simple
      - name: Remove .git directory to allow further process
        run: |
             rm -rf ./sec-o-simple/.git
             cd ..
      - name: Checkout config
        uses: actions/checkout@v4
        with:
          ref: main
          path: config
      - name: Remove .git directory to allow further process
        run: |
             rm -rf ./config/.git    
             cp -r ./config/.well-known ./sec-o-simple/.well-known
             cp _config.yaml ./sec-o-simple/_config.yaml
             cd sec-o-simple
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}